include top.mak
SRCS=OGLDAltAzView.cpp OGLDCubeMap.cpp OGLDCylinder.cpp OGLDMath.cpp OGLDPixelBuffer.cpp OGLDPixels.cpp OGLDPlane.cpp OGLDSphere.cpp OGLDTexture.cpp OGLDTorus.cpp OGLDTrackballView.cpp OGLDView.cpp OGLDShape.cpp OGLDif.cpp
BINARY=libOGLD
BINARY_EXT=$(X_LIBEXT)
DEPS=
include bottom.mak
